MeidaManageTool/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from video import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('video/', include('video.urls')),
                  path('myadmin/', include('myadmin.urls')),
                  path('users/', include('users.urls')),
                  path('comment/', include('comment.urls')),
                  path('', views.IndexView.as_view(), name='home'),  # 默认首页

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myadmin/urls.py
from django.urls import path

from . import views

app_name = 'myadmin'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    # ----------------------总览---------------------------
    path('', views.IndexView.as_view(), name='index'),

    # ----------------------视频管理------------------------
    path('video_list/', views.VideoListView.as_view(), name='video_list'),
    path('video_add/', views.AddVideoView.as_view(), name='video_add'),

    path('chunked_upload/', views.MyChunkedUploadView.as_view(), name='api_chunked_upload'),
    path('chunked_upload_complete/', views.MyChunkedUploadCompleteView.as_view(), name='api_chunked_upload_complete'),

    path('video_publish/<int:pk>/', views.VideoPublishView.as_view(), name='video_publish'),
    path('video_publish_success/', views.VideoPublishSuccessView.as_view(), name='video_publish_success'),
    path('video_edit/<int:pk>/', views.VideoEditView.as_view(), name='video_edit'),
    path('video_delete/', views.video_delete, name='video_delete'),

    # ----------------------分类管理----------------------------
    path('classification_add/', views.ClassificationAddView.as_view(), name='classification_add'),
    path('classification_list/', views.ClassificationListView.as_view(), name='classification_list'),
    path('classification_edit/<int:pk>/', views.ClassificationEditView.as_view(), name='classification_edit'),
    path('classification_delete/', views.classification_delete, name='classification_delete'),

    # ----------------------评论管理----------------------------
    path('comment_list/', views.CommentListView.as_view(), name='comment_list'),
    path('comment_delete/', views.comment_delete, name='comment_delete'),

    # ----------------------用户管理-------------------------
    path('user_add/', views.UserAddView.as_view(), name='user_add'),
    path('user_list/', views.UserListView.as_view(), name='user_list'),
    path('user_edit/<int:pk>', views.UserEditView.as_view(), name='user_edit'),
    path('user_delete/', views.user_delete, name='user_delete'),

    # -----------------------订阅通知-------------------------
    path('subscribe/', views.SubscribeView.as_view(), name='subscribe'),

    # -----------------------用户反馈-------------------------
    path('feedback_list/', views.FeedbackListView.as_view(), name='feedback_list'),
    path('feedback_delete/', views.feedback_delete, name='feedback_delete'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('subscribe/<int:pk>/', views.SubscribeView.as_view(), name='subscribe'),
    path('feedback/', views.FeedbackView.as_view(), name='feedback'),
    path('<int:pk>/collect_videos/', views.CollectListView.as_view(), name='collect_videos'),
    path('<int:pk>/like_videos/', views.LikeListView.as_view(), name='like_videos'),
]

video/urls.py
from django.urls import path
from . import views

app_name = 'video'
urlpatterns = [
    path('index', views.IndexView.as_view(), name='index'),
    path('search/', views.SearchListView.as_view(), name='search'),
    path('detail/<int:pk>/', views.VideoDetailView.as_view(), name='detail'),
    path('like/', views.like, name='like'),
    path('collect/', views.collect, name='collect'),
]

myadmin/models.py
from chunked_upload.models import ChunkedUpload


# Create your models here.
class MyChunkedUpload(ChunkedUpload):
    pass


# Override the default ChunkedUpload to make the `user` field nullable
MyChunkedUpload._meta.get_field('user').null = True

myadmin/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ValidationError

from users.models import User
from video.models import Video, Classification


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(min_length=4, max_length=30,
                               error_messages={
                                   'min_length': '用户名不少于4个字符',
                                   'max_length': '用户名不能多于30个字符',
                                   'required': '用户名不能为空',
                               },
                               widget=forms.TextInput(attrs={'placeholder': '请输入用户名'}))
    password = forms.CharField(min_length=8, max_length=30,
                               error_messages={
                                   'min_length': '密码不少于8个字符',
                                   'max_length': '密码不能多于30个字符',
                                   'required': '密码不能为空',
                               },
                               widget=forms.PasswordInput(attrs={'placeholder': '请输入密码'}))

    class Meta:
        model = User
        fields = ['username', 'password']

    error_messages = {'invalid_login': '用户名或密码错误', }


class VideoPublishForm(forms.ModelForm):
    title = forms.CharField(min_length=4, max_length=200, required=True,
                            error_messages={
                                'min_length': '至少4个字符',
                                'max_length': '不能多于200个字符',
                                'required': '标题不能为空'
                            },
                            widget=forms.TextInput(attrs={'placeholder': '请输入内容'}))
    desc = forms.CharField(min_length=4, max_length=200, required=True,
                           error_messages={
                               'min_length': '至少4个字符',
                               'max_length': '不能多于200个字符',
                               'required': '描述不能为空'
                           },
                           widget=forms.Textarea(attrs={'placeholder': '请输入内容'}))
    cover = forms.ImageField(required=True,
                             error_messages={
                                 'required': '封面不能为空'
                             },
                             widget=forms.FileInput(attrs={'class': 'n'}))
    status = forms.CharField(min_length=1, max_length=1, required=False,
                             widget=forms.HiddenInput(attrs={'value': '0'}))

    class Meta:
        model = Video
        fields = ['title', 'desc', 'status', 'cover', 'classification']


class VideoEditForm(forms.ModelForm):
    title = forms.CharField(min_length=4, max_length=200, required=True,
                            error_messages={
                                'min_length': '至少4个字符',
                                'max_length': '不能多于200个字符',
                                'required': '标题不能为空'
                            },
                            widget=forms.TextInput(attrs={'placeholder': '请输入内容'}))
    desc = forms.CharField(min_length=4, max_length=200, required=True,
                           error_messages={
                               'min_length': '至少4个字符',
                               'max_length': '不能多于200个字符',
                               'required': '描述不能为空'
                           },
                           widget=forms.Textarea(attrs={'placeholder': '请输入内容'}))
    cover = forms.ImageField(required=True,
                             error_messages={
                                 'required': '封面不能为空'
                             },
                             widget=forms.FileInput(attrs={'class': 'n'}))

    status = forms.CharField(min_length=1, max_length=1, required=False,
                             widget=forms.HiddenInput())

    # classification = forms.ModelChoiceField(queryset=Classification.objects.all())
    # classification = forms.CharField(min_length=1,max_length=1,required=False,
    #                          widget=forms.HiddenInput())

    class Meta:
        model = Video
        fields = ['title', 'desc', 'status', 'cover', 'classification']


class UserAddForm(forms.ModelForm):
    username = forms.CharField(min_length=4, max_length=30,
                               error_messages={
                                   'min_length': '用户名不少于4个字符',
                                   'max_length': '用户名不能多于30个字符',
                                   'required': '用户名不能为空',
                               },
                               widget=forms.TextInput(attrs={'placeholder': '请输入用户名'}))
    password = forms.CharField(min_length=8, max_length=30,
                               error_messages={
                                   'min_length': '密码不少于8个字符',
                                   'max_length': '密码不能多于30个字符',
                                   'required': '密码不能为空',
                               },
                               widget=forms.PasswordInput(attrs={'placeholder': '请输入密码'}))

    class Meta:
        model = User
        fields = ['username', 'password', 'is_staff']


def username_validate(value):
    if value == "admin":
        raise ValidationError('不能编辑超级管理员')


class UserEditForm(forms.ModelForm):
    username = forms.CharField(min_length=4, max_length=30, required=True,
                               validators=[username_validate],
                               error_messages={
                                   'min_length': '至少4个字符',
                                   'max_length': '不能多于30个字符',
                                   'required': '用户名不能为空'
                               },
                               widget=forms.TextInput(attrs={'placeholder': '请输入用户名'}))

    class Meta:
        model = User
        fields = ['username', 'is_staff']


class ClassificationAddForm(forms.ModelForm):
    title = forms.CharField(min_length=2, max_length=30, required=True,
                            error_messages={
                                'min_length': '至少2个字符',
                                'max_length': '不能多于30个字符',
                                'required': '不能为空'
                            },
                            widget=forms.TextInput(attrs={'placeholder': '请输入分类名称'}))

    class Meta:
        model = Classification
        fields = ['title', 'status']


class ClassificationEditForm(forms.ModelForm):
    title = forms.CharField(min_length=2, max_length=30, required=True,
                            error_messages={
                                'min_length': '至少2个字符',
                                'max_length': '不能多于30个字符',
                                'required': '不能为空'
                            },
                            widget=forms.TextInput(attrs={'placeholder': '请输入分类名称'}))

    class Meta:
        model = Classification
        fields = ['title', 'status']

templates/myadmin/classification_add.html
{% extends 'myadmin/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}

<div class="ui grid">
    <div class="row">
        <h3>分类添加</h3>
    </div>
    <div class="ui divider"></div>
    <div class="row">
        <div class="v-form-wrap">

            <form class="ui form" novalidate method="post" action="{% url 'myadmin:classification_add' %}"
                  enctype="multipart/form-data" role="form">
                {% csrf_token %}
                <div class="field">
                    <label>分类名称</label>
                    {{ form.title }}
                </div>
                <div class="field">
                    <div class="ui checkbox">
                      {{form.status}}
                      <label>是否启用</label>
                    </div>
                </div>

                <button class="ui primary button" type="submit">添加</button>

                {% include "base/form_errors.html" %}
                {% include "base/form_messages.html" %}

            </form>


        </div>
    </div>
</div>


{% endblock content %}

templates/myadmin/classification_add_success.html
{% extends 'myadmin/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}

<div class="ui grid">
    <div class="row">
        <h3>分类添加</h3>
    </div>
    <div class="ui divider"></div>
    <div class="row">
        <div class="v-form-wrap">

            <h3>添加成功！</h3>
            <h3><a href="{% url 'myadmin:classification_list' %}">&lt;&lt;返回列表</a></h3>
        </div>
    </div>
</div>


{% endblock content %}

templates/myadmin/classification_list.html
{% extends 'myadmin/base.html' %}
{% load static %}

{% block content %}

<div class="ui grid">
    <div class="row">
        <h3 class="ui header six wide column">分类列表</h3>
        <div class="v-title-extra ten wide column">
            <div class="ui action input v-admin-search">
                <input type="text" placeholder="Search..."  value="{{q}}" id="v-search">
                <button class="ui small button" id="search">搜索</button>
            </div>
        </div>
    </div>
    <div class="ui divider"></div>
    <div class="row">
        <table class="ui unstackable single line striped selectable table">
            <thead>
            <tr><th>#id</th><th>名称</th></th><th>状态</th><th>操作</th></tr>
            </thead>
            <tbody class="video-list">

            {% for item in classification_list %}
            <tr classification-id="{{item.id}}">
                <td> {{item.id}}</td>
                <td> {{item.title}}</td>
                <td> {% if item.status %}启用{% else %}未启用{% endif %}</td>
                <td>
                    <a class="ui primary button classification-edit" href="{% url 'myadmin:classification_edit' item.id %}">编辑</a>
                    <a class="ui button classification-delete">删除</a>
                </td>
            </tr>
            {% empty %}
            <h3>暂无数据</h3>
            {% endfor %}

            </tbody>
            <tfoot>
            <tr>
                <th colspan="6">
                    {% include 'myadmin/page_nav.html' %}
                </th>
            </tr>
            </tfoot>
        </table>
    </div>
</div>


{% endblock content %}

{% block modal %}
{% include "myadmin/classification_list_modal.html" %}
{% endblock modal %}

{% block javascript %}
<script>
    var search_url = "{% url 'myadmin:classification_list' %}"
    var api_classification_delete = "{% url 'myadmin:classification_delete' %}"
</script>
<script src="{% static 'js/myadmin/classification_list.js' %}"></script>
{% endblock javascript %}

templates/myadmin/classification_list_modal.html
<!--- 删除模态框 -->
<div class="ui tiny modal delete">
    <div class="header">
        删除确认
    </div>
    <div class="image content">
        <div class="description">
            确认删除分类(该分类下面的视频将会被删除)？
        </div>
    </div>
    <div class="actions">
        <div class="ui primary approve button">确认</div>
        <div class="ui deny button">取消</div>
    </div>
</div>

templates/myadmin/comment_list_modal.html
<!--- 删除模态框 -->
<div class="ui tiny modal delete">
    <div class="header">
        删除评论
    </div>
    <div class="image content">
        <div class="description">
            确认删除该条评论？
        </div>
    </div>
    <div class="actions">
        <div class="ui primary approve button">确认</div>
        <div class="ui deny button">取消</div>
    </div>
</div>

templates/myadmin/feedback_list_modal.html
<!--- 删除模态框 -->
<div class="ui tiny modal delete">
    <div class="header">
        确认删除
    </div>
    <div class="image content">
        <div class="description">
            确认删除该条内容？
        </div>
    </div>
    <div class="actions">
        <div class="ui primary approve button">确认</div>
        <div class="ui deny button">取消</div>
    </div>
</div>

templates/myadmin/index.html
{% extends 'myadmin/base.html' %}
{% load static %}

{% block content %}

<div class="ui grid">
    <div class="row">
        <h3>总览</h3>
    </div>
    <div class="ui divider"></div>
    <div class="row">

        <div>

            <div class="ui hidden divider"></div>
            <div class="ui hidden divider"></div>

            <div class="ui tiny statistics">
                <div class="statistic">
                    <div class="value">{{ video_count }}</div>
                    <div class="label">视频数</div>
                </div>
                <div class="statistic">
                    <div class="value">{{ video_has_published_count }}</div>
                    <div class="label">发布中</div>
                </div>
                <div class="statistic">
                    <div class="value">{{ video_not_published_count }}</div>
                    <div class="label">未发布</div>
                </div>
            </div>

            <div class="ui hidden divider"></div>
            <div class="ui hidden divider"></div>
            <div class="ui hidden divider"></div>

            <div class="ui tiny statistics">
                <div class="statistic">
                    <div class="value">{{ user_count }}</div>
                    <div class="label"> 用户数</div>
                </div>
                <div class="statistic">
                    <div class="value">{{ user_today_count }}</div>
                    <div class="label">今日新增</div>
                </div>
            </div>

            <div class="ui hidden divider"></div>
            <div class="ui hidden divider"></div>
            <div class="ui hidden divider"></div>

            <div class="ui tiny statistics">
                <div class="statistic">
                    <div class="value">{{ comment_count }}</div>
                    <div class="label">评论数</div>
                </div>
                <div class="statistic">
                    <div class="value">{{ comment_today_count }}</div>
                    <div class="label">今日新增</div>
                </div>
            </div>

            <div class="ui hidden divider"></div>
            <div class="ui hidden divider"></div>
            <div class="ui hidden divider"></div>
            <div class="ui hidden divider"></div>
            <div class="ui hidden divider"></div>
            <div class="ui hidden divider"></div>
            <h4>
                {% if not user.is_superuser %}
                {{user}}权限：查看数据、搜索数据。暂无编辑和删除数据权限。
                <br/>下载代码后，可自行添加超级用户，即可使用全部功能权限。
                <br/>添加方法：python3 manage.py createsuperuser
                <br/>如有问题，可咨询开发者（weixin id: java2048）
                {% endif %}
            </h4>

        </div>

    </div>
</div>

{% endblock content %}

templates/myadmin/mail_template.html
{% load static %}
{% load thumbnail %}
{% load video_tag %}
<html>
<head>
    <meta charset="utf-8"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.staticfile.org/semantic-ui/2.4.1/semantic.min.css">
</head>
<body>
<h3>{{ video.title }}</h3>
<p>
    <a class="image" href="{{site_url}}{% url 'video:detail' video.id %}">
        <img class="ui image"
             style="object-fit: cover; object-position: center;height: 200px;width: 300px;"
             src="{{site_url}}{{video.cover}}">
    </a>
</p>
<p>{{video.desc}}</p>

<a class="ui button" href="{{site_url}}{% url 'video:detail' video.id %}">点击进入</a>

</body>
</html>

templates/myadmin/subscribe.html
{% extends 'myadmin/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}

<div class="ui grid">
    <div class="row">
        <h3>订阅通知</h3>
    </div>
    <div class="ui divider"></div>
    <div class="row">
        <div class="v-form-wrap">
            <div class="ui small input focus">
                <!--<input type="text" id="video_id" required placeholder="请输入视频id">-->
                <form class="ui form" novalidate method="post" action=""
                      enctype="multipart/form-data" role="form">
                    <div class="field">
                        <label>请选择要推送的视频</label>

                        <div class="ui selection dropdown">
                            <i class="dropdown icon"></i>
                            <div class="default text">请选择</div>
                            <div class="menu">
                                {% for item in video_list %}
                                <div class="item" data-value="{{item.id}}">{{item.title}}</div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <h4>
                        <div class="ui tiny primary button" id="send-mail" video-id="{{video_id}}">通知订阅用户</div>
                    </h4>
                </form>

            </div>

            <div id="send-mail-progress"></div>
        </div>
    </div>
</div>


{% endblock content %}

{% block javascript %}
<script>
    var api_send_mail = "{% url 'myadmin:subscribe' %}";

    $(function(){
        $('.ui .dropdown').dropdown();
    });


</script>
<script src="{% static 'js/myadmin/send_mail.js' %}"></script>
{% endblock javascript %}

templates/myadmin/user_add.html
{% extends 'myadmin/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}

<div class="ui grid">
    <div class="row">
        <h3>用户添加</h3>
    </div>
    <div class="ui divider"></div>
    <div class="row">
        <div class="v-form-wrap">

            <form class="ui form" novalidate method="post" action="{% url 'myadmin:user_add' %}"
                  enctype="multipart/form-data" role="form">
                {% csrf_token %}
                <div class="field">
                    <label>用户名</label>
                    {{ form.username }}
                </div>
                <div class="field">
                    <label>密码</label>
                    {{ form.password }}
                </div>
                <div class="field">
                    <div class="ui checkbox">
                      {{form.is_staff}}
                      <label>管理员账号</label>
                    </div>
                </div>

                <button class="ui primary button" type="submit">添加</button>

                {% include "base/form_errors.html" %}
                {% include "base/form_messages.html" %}

            </form>


        </div>
    </div>
</div>


{% endblock content %}

templates/myadmin/user_edit.html
{% extends 'myadmin/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}

<div class="ui grid">
    <div class="row">
        <h3>用户编辑</h3>
    </div>
    <div class="ui divider"></div>
    <div class="row">
        <div class="v-form-wrap">

            <form class="ui form" novalidate method="post" action="{% url 'myadmin:user_edit' form.instance.pk %}"
                  enctype="multipart/form-data" role="form">
                {% csrf_token %}
                <div class="field">
                    <label>用户名</label>
                    {{ form.username }}
                </div>
                <div class="field">
                    <div class="ui checkbox">
                      {{form.is_staff}}
                      <label>管理员账号</label>
                    </div>
                </div>

                <button class="ui primary button" type="submit">保存</button>

                {% include "base/form_errors.html" %}
                {% include "base/form_messages.html" %}

            </form>


        </div>
    </div>
</div>


{% endblock content %}

{% block modal %}
{% endblock modal %}

templates/myadmin/video_list_modal.html
<!--- 删除模态框 -->
<div class="ui tiny modal delete">
    <div class="header">
        删除视频
    </div>
    <div class="image content">
        <div class="description">
            确认删除该条视频？
        </div>
    </div>
    <div class="actions">
        <div class="ui primary approve button" href="{{ request.path }}">确认</div>
        <div class="ui deny button">取消</div>
    </div>
</div>

templates/myadmin/video_publish.html
{% extends 'myadmin/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}

<div class="ui grid">
    <div class="row">
        <h3>视频资料</h3>
    </div>
    <div class="ui divider"></div>
    <div class="row">
        <div class="v-form-wrap">

            <form class="ui form" novalidate method="post" action="{% url 'myadmin:video_publish' form.instance.pk %}"
                  enctype="multipart/form-data" role="form">
                {% csrf_token %}
                <input name="video_id" id="video_id" type="hidden">
                <div class="field">
                    <label>视频标题</label>
                    {{ form.title }}
                </div>
                <div class="field">
                    <label>视频描述</label>
                    {{ form.desc }}
                </div>
                <div class="field">
                    <label>视频分类</label>
                    <div class="ui selection  dropdown">
                        {{ form.classification  }}
                        <i class="dropdown icon"></i>
                        <div class="default text">请选择</div>
                        <div class="menu">
                            {% for item in clf_list %}
                            <div class="item" data-value="{{item.id}}">{{item.title}}</div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                 {{form.status}}
                <div class="field">
                    <label>视频封面</label>
                    {% if video.cover %}
                    {% thumbnail video.cover "300x200" crop="center" as im %}
                      <img class="ui small image" src="{{ im.url }}">
                    {% empty %}
                    {% endthumbnail %}
                    {% endif %}

                    <div class="v-form-field">
                        <label class="ui large green label" for="id_cover">
                            <i class="upload icon"></i> 上传封面
                             {{form.cover}}
                        </label>
                        <span id="file_is_choose" class="n">文件已选择</span>
                    </div>
                </div>


                <button class="ui primary button" type="submit">发布</button>

                {% include "base/form_errors.html" %}
                {% include "base/form_messages.html" %}

            </form>


        </div>
    </div>
</div>


{% endblock content %}

{% block modal %}
{% endblock modal %}

{% block javascript %}

<script>
$(function(){

    $('.ui .dropdown').dropdown();

    $("#id_cover").change(function(){
        $("#file_is_choose").show()
    });

});
</script>


{% endblock javascript %}

templates/myadmin/video_publish_success.html
{% extends 'myadmin/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}

<div class="ui grid">
    <div class="row">
        <h3>视频资料</h3>
    </div>
    <div class="ui divider"></div>
    <div class="row">
        <div class="v-form-wrap">

            <h3>发布成功！</h3>
            <h3><a href="{% url 'myadmin:video_list' %}">&lt;&lt;返回列表</a></h3>

        </div>
    </div>
</div>


{% endblock content %}